# docker-compose.yml
version: '2'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    restart: always
    volumes:
      - /portainer/AppData/Bitwarden-rs/Data:/data
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DOMAIN: ${DOMAIN}
    ports: [
      '${PORT}:80/tcp'
      ]
  backup:
    image: bruceforce/bw_backup:latest
    restart: always
    volumes:
      - /portainer/AppData/Bitwarden-rs/Data:/data
      - /portainer/AppData/Bitwarden-rs/DB-Backup:/backup
    environment:
      BACKUP_FILE: /backup/db.sqlite3
      CRON_TIME: ${CRON_TIME}
      UUID: ${UUID}
      GID: ${GID}
    
