---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${DATABASE_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - /portainer/AppData/Bookstack/Data:/config
    ports:
      - ${PORT}:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${Timezone}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /portainer/AppData/Bookstack/DB:/config
    restart: unless-stopped
  bookstack_db-backup:
    build: /periodic-backup
    container_name: bookstack_db_backup
    environment:
      MYSQL_CONTAINER_NAME: bookstack_db
      MYSQL_DATABASE: bookstackapp
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /portainer/AppData/Bookstack/DB_Backup:/opt/mysql/backup
    command: crond -f -d 8
    restart: always
