version: "2"

services:
  db:
    image: mariadb:latest
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
  matomo:
    image: matomo:latest
    restart: always
    volumes:
      - ${MATOMO_VOLUME}:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - MATOMO_DATABASE_DBNAME=matomo
    ports:
      - ${PORT}:80
