---
version: "2.1"

services:
  matomo:
    image: matomo
    container_name: matomo
    environment:
      - MATOMO_DATABASE_HOST=matom_db
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=${DB_PASSWORD}
      - MATOMO_DATABASE_DBNAME=matomo_db
    volumes:
      - /portainer/AppData/Matomo/Config:/var/www/html
    ports:
      - ${PORT}:80
    restart: unless-stopped
    depends_on: matomo_db
  matomo_db:
    image: linuxserver/mariadb
    container_name: matomo_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=matomo_db #optional
      - MYSQL_USER=matomo #optional
      - MYSQL_PASSWORD=${DB_PASSWORD} #optional
    volumes:
      - /portainer/AppData/Matomo/DB:/config
    restart: unless-stopped
